test suite, refactor app
camiilavillamizar/Blockchain_app pull request #7
Opened 2020-08-31 23:33 UTC by LuisChDev

Este commit introduce una suite de tests para la aplicación. Debido
a dificultades con la creación de múltiples instancias de Flask en su
arquitectura básica (objecto "app" global), se decide factorizarla
empleando el patrón fábrica detallado en
"https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/".

2020-08-31 23:34 UTC, LuisChDev commented
se me olvidaba decir que todo funciona normal, al menos en mi PC. prueben la rama si pueden antes de hacer el merge.

2020-09-07 04:25 UTC, AndresMorelos commented
> 
> 
> se me olvidaba decir que todo funciona normal, al menos en mi PC. prueben la rama si pueden antes de hacer el merge.

LoL, como me respondieron una vez a mi, no le vas a entregar tu pc al cliente.

2020-09-07 04:30 UTC, AndresMorelos requested changes

2020-09-07 04:30 UTC, AndresMorelos commented on node_server/node_server.py
> +import sys
Import no usado, por favor eliminar

2020-09-07 04:30 UTC, AndresMorelos commented on test/test_node_server.py
> +    # FIXME los nodos no realizan consenso cuando se minan en paralelo
No completado el FIXME para verificar el consenso de los nodos.

2020-09-07 18:13 UTC, camiilavillamizar approved these changes

2020-09-11 12:52 UTC, closed without merging